DROP TABLE Amount;
CREATE TABLE Amount (id bigint generated BY DEFAULT AS IDENTITY, category VARCHAR(255),
comments VARCHAR(255), name VARCHAR(255), price INTEGER NOT NULL, PRIMARY KEY (id));

INSERT INTO Amount(name, price,category,comments)
VALUES('Sandwich',450,'Food','What a scrumptious sandwich'),
('White T-Shirt',980,'Clothes','Uniqlo T-Shirt'),
('iPhone',130000,'Gadget','iPhone 13 Pro'),
('Green Curry',880,'Food','Thai Cuisine'),
('iPad',140000,'Gadget','iPad Pro'),
( 'Crispy Pizza',850,'Food','gluten free');
